# Tomcat
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
    connection-timeout: 5000ms
    threads:
      max: 1000
      min-spare: 30
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
# spring配置
spring:
  application:
    name: registration
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/hospital?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 20
        max-wait: 10
        max-idle: 10
        min-idle: 5
    timeout: 1000
  session:
    store-type: redis
  data:
    rest:
      base-path: /api/rest/v1
      default-page-size: 10
      max-page-size: 100
      page-param-name: page
      limit-param-name: size
      sort-param-name: sort
      default-media-type: application/json
      return-body-on-create: true
      return-body-on-update: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    #是否开启文档功能
    enabled: true
    #swagger后端请求地址
    path: /api-docs
  swagger-ui:
    #自定义swagger前端请求路径，输入http://127.0.0.1:8080/test会自动重定向到swagger页面
    path: /test
  #包扫描路径
  packages-to-scan: com.xjm.hospital.registration.controller
  #这里定义了两个分组，可定义多个，也可以不定义
#  group-configs:
#     #分组名
#    - group: admin
#     #按路径匹配
#      pathsToMatch: /admin/**
#     #分组名
#    - group: user
#     #按包路径匹配
#      packagesToScan: com.xjm.hospital.registration.controller
